services:
  core-mobile-server:
    build:
      context: ../
      dockerfile: CoreMobileServer/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ../CustomerFiles/serviceAccountKey.json:/app/CoreMobileServer/serviceAccountKey.json:ro
      - ../CustomerFiles/serviceAccountKey.json:/app/CoreMobileServer/serviceAccountKey.json:ro
    depends_on:
      core-mobile-db:
        condition: service_healthy
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - core-mobile-server
  core-mobile-db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "ktor_tutorial_db"
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 1s