services:
  core-mobile-server:
    build:
      context: ../
      dockerfile: CoreMobileServer/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./CustomerFiles/serviceAccountKey.json:/app/CoreMobileServer/serviceAccountKey.json:ro
      - ./CustomerFiles/tables.yaml:/app/CoreMobileServer/tables.yaml:ro
      - ./CustomerFiles/config.yaml:/app/CoreMobileServer/config.yaml:ro
    depends_on:
      core-mobile-db:
        condition: service_healthy
  core-mobile-nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./CustomerFiles/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - core-mobile-server
      - core-mobile-db
  core-mobile-db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "ktor_tutorial_db"
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 1s